In [66]:
#Use of Numpy & open cv to convert images into numpy arrays

import numpy
number = numpy.arange(81)

In [67]:
number.reshape(9,3,3)  #Matrix creation

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]],

       [[54, 55, 56],
        [57, 58, 59],
        [60, 61, 62]],

       [[63, 64, 65],
        [66, 67, 68],
        [69, 70, 71]],

       [[72, 73, 74],
        [75, 76, 77],
        [78, 79, 80]]])

In [68]:
import cv2
from PIL import Image

In [69]:
import os
os.listdir()

['.git',
 '.gitattributes',
 '.ipynb_checkpoints',
 'App and Pages',
 'Basic',
 'keyboard-shortcuts-windows.pdf',
 'self.jpg',
 'smallgray.png',
 'temps_today.csv',
 'Untitled.ipynb']

In [70]:
small_image =Image.open('self.jpg')
print(small_image.size)



(956, 956)


In [71]:
 #255 in the array in white
#the number in the array represents color intensity value 
im_g=cv2.imread("smallgray.png",0) 
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [78]:
#Horizontal stacking
#Tuple is used since this method only take one argument
im_g1=numpy.hstack((im_g,im_g,im_g))
print(im_g1)


[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]
